include:
  - board: nice_nano_v2
    shield: crosses_left
    artifact-name: crosses_36_left
    # OSレベルで「警告で止まるな」と強制します
    cmake-args: -DKCONFIG_ERROR_ON_WARNING=n
  - board: nice_nano_v2
    shield: crosses_right
    artifact-name: crosses_36_right
    snippet: studio-rpc-usb-uart
    # 右側も同様に強制突破させます
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DKCONFIG_ERROR_ON_WARNING=n
