---
include:
  - board: nice_nano
    shield: crosses_left
    artifact-name: crosses_35_left
  - board: nice_nano
    shield: crosses_right
    artifact-name: crosses_35_right
  - board: nice_nano
    shield: settings_reset
