# 画面は物理的に存在しないので完全にオフ（現在の状態）
CONFIG_ZMK_DISPLAY=n

# 【特効薬①】ZMKアップデートで変わったマルチメディアキー（音量・輝度等）の形式をMac用に互換化
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y

# 【特効薬②】最近のmacOSのBluetooth接続バグを完全に回避する通信間隔の調整
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=12
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=24
